debug = false
logLevel = "ERROR"

defaultEntryPoints = ["http", "https"]

[web]
  address = ":8080"

[entryPoints]
  [entryPoints.http]
    address = ":80"
  [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]

[retry]

[docker]
  endpoint = "unix:///var/run/docker.sock"
  exposedByDefault = false

[acme]
  email = "YOUR_EMAIL"
  storage = "acme.json"
  entryPoint = "https"
  onHostRule = true
  [acme.httpChallenge]
    entryPoint = "http"
